version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pingboard
      POSTGRES_USER: pingboard_user
      POSTGRES_PASSWORD: pingboard_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=postgresql://pingboard_user:pingboard_password@db:5432/pingboard
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
