# Generated by Django 4.2.7 on 2025-08-24 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=280, validators=[django.core.validators.MaxLengthValidator(280)])),
                ('category', models.CharField(blank=True, choices=[('event', 'Event'), ('sale', 'Sale'), ('help', 'Help'), ('misc', 'Misc')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
