# Generated by Django 4.2.7 on 2025-08-24 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_pings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ping',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_pings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['-timestamp'], name='pings_ping_timesta_82360d_idx'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['category'], name='pings_ping_categor_c315f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['location'], name='pings_ping_locatio_eee50b_idx'),
        ),
    ]
