# Generated by Django 4.2.7 on 2025-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='hashtags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ping',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
    ]
